- name: copy mysql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: disable mysql 8 version
  ansible.builtin.shell: dnf module disable mysql -y

- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-community-server
    state: present

- name: start mysql
  ansible.builtin.systemd:
    name: mysqld
    state: restarted

- name: set root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
